# Generated by Django 4.2.5 on 2024-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srp_app", "0003_visitante"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="data_final",
            field=models.DateTimeField(null=True, verbose_name="Data final"),
        ),
    ]
