# Generated by Django 4.2.5 on 2024-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srp_app", "0004_evento_data_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="visitantes",
            field=models.ManyToManyField(
                blank=True, to="srp_app.visitante", verbose_name="Visitantes"
            ),
        ),
    ]
