# Generated by Django 4.2.5 on 2024-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srp_app', '0005_evento_visitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Capa'),
        ),
    ]
