#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "Cancelando commit. Seu título não segue o padrão do Conventional Commits." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,72}$"; then
    echo "Cancelando commit. Seu título é muito longo." >&2
    exit 1
fi
